CREATE TABLE "Books" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "png_path" varchar,
  "age_group" int,
  "rating" float,
  "isbn" int,
  "category" int,
  "author_id" int,
  "amount" int
);

CREATE TABLE "BookCategories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category" varchar
);

CREATE TABLE "Authors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "surname" varchar
);

CREATE TABLE "Orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "last_status_update" datetime NOT NULL,
  "user_id" int,
  "status" int NOT NULL,
  "payment_type" int NOT NULL,
  "address" varchar,
  "city" varchar,
  "post_code" varchar
);

CREATE TABLE "Users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "surname" varchar,
  "email" email UNIQUE,
  "password" password
);

CREATE TABLE "OrderDetails" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "book_id" int,
  "status" int NOT NULL
);

ALTER TABLE "BookCategories" ADD FOREIGN KEY ("id") REFERENCES "Books" ("category");

ALTER TABLE "Books" ADD FOREIGN KEY ("author_id") REFERENCES "Authors" ("id");

ALTER TABLE "Orders" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "OrderDetails" ADD FOREIGN KEY ("order_id") REFERENCES "Orders" ("id");

ALTER TABLE "OrderDetails" ADD FOREIGN KEY ("book_id") REFERENCES "Books" ("id");
